version: "3.3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.4
    expose:
      - "27017"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/itineraries-docker
  itineraries:
    container_name: itineraries
    build: .
    image: challenge/itineraryService:1.0.0
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 5m
      timeout: 10s
      retries: 3
  routes:
    container_name: routes
    build: .
    image: challenge/routesService:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - itineraries
      
